### PR TITLE
Update targetSDK/compileSDK to 34

### PR DESCRIPTION
**Pull request by xiaodao-google**
1. Update compileSDK/targetSDK to 34.
2. Update com.google.android.material:material to 1.11.0.

### CODE REVIEW

**Comment by JonEckenrode** [comment]
What do you think about `updating id 'org.jetbrains.kotlin.android' version '1.7.20' apply false` to 1,8.0 in the main build.gradle file?

**Comment by xiaodao-google** [comment]
I see the most advanced for 1.8 is 1.8.22, do you want me to use that intead?

**Comment by JonEckenrode** [comment]
Sounds good.

**Review by JonEckenrode — CHANGES_REQUESTED** [review]
Review completed.

**Comment by xiaodao-google** [comment]
> Review completed.

Thanks Jon.

**Pull request merged**
